### ISSUE TITLE
Invalid memory access case when invalid polygons are given

### ISSUE THREAD

**Issue by julienjpk** [ivanfratric/polypartition#31]
I'm currently using this very useful piece of code in one of my programs, and came across a nasty little behaviour in one of my study cases. I understand this is not really a *bug* in the library, given that the code assumes all input polygons are valid (n>2), however there were consequences in the rest of my code in this case so I thought I'd bring it up in case someone ever comes across it again.

When an invalid polygon is given to `Triangulate_OPT`, [the first index used on the `dpstates` array](https://github.com/ivanfratric/polypartition/blob/f54d2537491f37fce4dbe82b58f6b65d77a20a5d/src/polypartition.cpp#L626) may be invalid (among other things). While it may not necessarily trigger an error at that exact spot, it can cause corruptions which later propagate and mislead debugging (as it was the case for me).

Would it be possible for the library to check the validity of its `TPPLPoly` objects before it manipulates them? I've added this check in my code (I should anyway), but without `valgrind` and `massif` ([which conveniently had a little oops for my distro a few days ago](https://bugs.archlinux.org/task/59551)), it was particularly tricky to trace back the error to an invalid polygon. Now that I'm using upstream `valgrind`, I can confirm that it reports *Use of uninitialised value*, *Bad permissions for mapped region* or *Access not within mapped region*.

**Comment by ivanfratric** [comment]
Hi Julien, would you be willing to submit a patch? You seem to have looked into this quite a bit.

**Comment by julienjpk** [comment]
Hi! I just opened a pull request, I just didn't have the time to do it back when I opened the issue. Could you make sure it's okay? It may solve the issue but I'm not familiar enough with the code to be sure I haven't missed anything. Besides, the rest of the code assumes the user doesn't mess up, so it's a first.
