### ISSUE TITLE
Library license?

### ISSUE THREAD

**Issue by PDeveloper** [ivanfratric/polypartition#39]
Hey!

What is the license of this library? Can I use it in a potentially commercial project like my own game etc.? Answers on this would be great, since it impacts which libraries I can use!

Thanks!
P.

**Comment by ivanfratric** [comment]
MIT license. See the header in https://github.com/ivanfratric/polypartition/blob/master/src/polypartition.h
Using it in a commercial project is totally fine.

**Comment by PDeveloper** [comment]
Beautiful, thank you! Great library and great algorithms, especially the ability to decompose into convex polygons instead of triangles!

I will share what I'm creating later on, hopefully I will also be able to share useful code for 2d navigation meshes etc.
